/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface GroupImages {
  created_at: Generated<string>;
  filename: string;
  group_id: number;
  has_been_printed: Generated<number>;
  id: Generated<number>;
}

export interface Groups {
  id: Generated<number>;
  name: string;
}

export interface Images {
  created_at: Generated<string | null>;
  filename: string | null;
  has_been_printed: Generated<number>;
  id: Generated<number>;
  student_id: number;
}

export interface Students {
  address: string | null;
  blood_type: string | null;
  date_of_birth: string | null;
  deleted_at: string | null;
  group_id: number;
  has_bonded_with: Generated<number | null>;
  hobby: string | null;
  id: Generated<number>;
  instagram_handle: string | null;
  name: string | null;
  nickname: string | null;
  nim: string | null;
  place_of_birth: string | null;
}

export interface DB {
  group_images: GroupImages;
  groups: Groups;
  images: Images;
  students: Students;
}
